### ISSUE TITLE
Не ставиться из репозитория

### ISSUE THREAD

**Issue by Knayz** [FRiMN/Rackman#11]
Ubuntu 18.04
При добавлении репозитория выдает.
`E: Репозиторий «http://ppa.launchpad.net/freezemandix/rackman/ubuntu bionic Release» не содержит файла Release.

N: Обновление из этого репозитория нельзя выполнить безопасным способом, и поэтому по умолчанию он отключён.

N: Смотрите справочную страницу apt-secure(8) о создании репозитория и настройке пользователя.
`

**Comment by FRiMN** [comment]
Спасибо, что заметили.
Да, не было пакета для вашей убунты. Сейчас всё есть.
Также обновил программу до версии 1.12.0. В ней добавлена лупа.
