### ISSUE TITLE
Релизы в Releases, а не dist

### ISSUE THREAD

**Issue by stobenski** [FRiMN/Rackman#4]
Предлагаю выпускать релизы через [Releases](https://github.com/FRiMN/Rackman/releases), а не складировать в dist. 
Я пишу ебилд для генты, который позже запуллреквещю, да и другим пакетщикам было бы удобнее отслеживать и получать релизы там, а не смотреть в диру dist. Спасибо.

**Comment by FRiMN** [comment]
Я как-то пропустил этот момент. _/dist_ пока останется, потом подумаю, что с ней делать.
Сейчас есть релиз [v1.6.7](https://github.com/FRiMN/Rackman/releases/tag/v1.6.7).
Спасибо, сам бы не нашёл :)

**Comment by stobenski** [comment]
Спасибо. В общем ебилд для Gentoo находится в оверлее mva, вот [здесь](https://github.com/msva/mva-overlay/blob/master/x11-misc/rackman/rackman-9999.ebuild).
